# Generated by Django 4.2.7 on 2024-09-28 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ('-date_formation',), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterField(
            model_name='artwork',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 10, 0, 7, 827899, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
