# Generated by Django 4.2.7 on 2024-09-28 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_artwork_options_alter_artwork_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 10, 6, 13, 509542, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
