# Generated by Django 4.2.7 on 2024-10-01 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_artwork_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 10, 9, 47, 108892, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
