# Generated by Django 4.2.7 on 2024-10-08 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_artwork_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 8, 15, 12, 667004, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
