# Generated by Django 4.2.7 on 2024-10-08 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_artwork_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 13, 27, 34, 168768, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
